[manager]
  sort_by = "modified"
  sort_dir_first = true
  linemode = "size"

[[manager.prepend_keymap]]
  on   = "!"
  run  = 'shell "$SHELL" --block --confirm'
  desc = "Open shell here"

[preview]
  wrap = "yes"

